### ISSUE TITLE
Cannot override /usr/var location for policies

### ISSUE THREAD

**Issue by jengelh** [mupuf/libwsm#13]
```
/usr/bin/cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib -DCMAKE_BUILD_TYPE=None '-DCMAKE_C_FLAGS=-fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' '-DCMAKE_MODULE_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/share/cmake/Modules -DWSM_DEFAULT_POLICY_PREFIX=/usr/share/wsm-policy
```
Despite requesting /usr/share/wsm-policy with an override, the cmakefiles still install the policy files into /usr/var/share/.

**Comment by mupuf** [comment]
That is quite a command line you have here. I guess this is the normal one from KDE along with -DWSM_DEFAULT_POLICY_PREFIX ?

In any case, I get your point. I can make cmake install the policy in WSM_DEFAULT_POLICY_PREFIX or I can add another variable to specifically install the default policy in. I guess I could do the second and have it use the DEFAULT_POLICY+PREFIX when unset.

How does it sound to you? Will cook up a patch a bit later today.

**Comment by jengelh** [comment]
The command line simply stems from rpm macro expansion at the distro level to cover a bunch of cmake idiosyncracies (like `-DLIB_SUFFIX=64` ... which should be redundant given `-DLIB_INSTALL_DIR` is already there).

The default being `${prefix}/var` is fine (automake does that too), the problem is that the `-DWSM_DEFAULT_POLICY_PREFIX` argument has no function, because of this line:
```
        INSTALL(DIRECTORY "${CMAKE_SOURCE_DIR}/data/security/wsm" DESTINATION "var/share/security")
```
This should have been `DESTINATION ${WSM_DEFAULT_POLICY_PREFIX}` or so.

Similarly,
```
        SET(WSM_BACKEND_DIRECTORY ${CMAKE_INSTALL_PREFIX}/lib/wsm)
```
is another horrors - it ought to have been `${LIB_INSTALL_DIR}/wsm` or so.
In same vain, passing `-DWSM_BACKEND_DIRECTORY=/usr/lib64/wsm` to cmake also has no lasting effect - `make install` places it into /usr/lib/wsm again.

And people wonder why I dislike cmake :-/

**Comment by mupuf** [comment]
That should fix at least most of your issues. I am really interested in any issues you may have though.

**Comment by Cloudef** [comment]
Actually cmake has this https://cmake.org/cmake/help/v3.3/module/GNUInstallDirs.html which you should use. (Distros that don't use lib64 still need to -DCMAKE_INSTALL_LIBDIR=/usr/lib though)

I can vouch on cmake dislike, portability is best solved by actually porting.

**Comment by mupuf** [comment]
Thanks for the tip Cloudef! Definitely what I was looking for yesterday! I updated the CMakeLists again.
